### ISSUE TITLE
inject.js 如何编译到Resources.py 

### ISSUE THREAD

**Issue by ddatsh** [DoooReyn/WxReader#10]
发现inject.js 这些资源会被编译到  app\conf\Resources.py 被运行
这是如何做呀.

**Comment by DoooReyn** [comment]
> 发现inject.js 这些资源会被编译到 app\conf\Resources.py 被运行 这是如何做呀.
参见[Rcc.py](https://github.com/DoooReyn/WxReader/blob/main/scripts/rcc/Rcc.py)
