### ISSUE TITLE
【邀请函】意见征集令

### ISSUE THREAD

**Issue by DoooReyn** [DoooReyn/WxReader#11]
# 通知！！！

**WxReader 2.0.1**发布以来，普遍得到了大家的喜爱，作为作者在此表示欣慰和感动！真心谢谢大家的厚爱！

同时，在 issue 和邮件中也收到了一些热心粉丝的反馈和意见，但由于**WxReader**是业余时间开发的，因此不会经常维护，目前计划每个版本之间至少出现**3个或以上**问题后才会着手开发下个版本。

想来想去，打算在这里开一个帖子，集中大家的智慧来帮助**WxReader**变得更加友好易用，请大家不吝赐教、知无不言⭐⭐⭐

---

**WxReader 2.0.2** 重点照顾对象：

- 【新增】开启自动阅读时，全书读完后可以自动跳转到书籍首页以实现反复阅读，该功能适用于纯挂机目的；
  - 为了区分【挂机】和【阅读】目的，会在【选项】中增加一个【挂机模式】复选框，默认不勾选；
  - 使用【挂机模式】，全书读完时将不会出现弹窗提示，跳转到书籍首页继续自动阅读；
  - 使用【阅读模式】，将保持当前版本的流程；
  - 【修复】修复按Q键就会退出程序的问题
  - 评估难度★★☆☆☆

**Comment by ddatsh** [comment]
放在 vps 里运行，发现还是有挺多次翻页时，下一页完全没反应，内容是空的，点击一次刷新，出来了，是不是可以从机制上再进行优化下？

**Comment by ddatsh** [comment]
之前用chrome插件版，登录有效期是一周不到？如何检测一下登录过期了，然后再可以发一个 http 通知出去？

**Comment by DoooReyn** [comment]
> 放在 vps 里运行，发现还是有挺多次翻页时，下一页完全没反应，内容是空的，点击一次刷新，出来了，是不是可以从机制上再进行优化下？

页面加载失败时主动重试的意思？

**Comment by DoooReyn** [comment]
> 之前用chrome插件版，登录有效期是一周不到？如何检测一下登录过期了，然后再可以发一个 http 通知出去？

插件版跟这个项目没有关系，我也没用过，不知道登录有效期是多久。如何检测登录状态是一个问题，确实可以考虑一下。

**Comment by ddatsh** [comment]
> > 放在 vps 里运行，发现还是有挺多次翻页时，下一页完全没反应，内容是空的，点击一次刷新，出来了，是不是可以从机制上再进行优化下？
> 
> 页面加载失败时主动重试的意思？

是的

**Comment by DoooReyn** [comment]
> 能否提取微信读书的epub？
不能

**Comment by lzc3817** [comment]
主要有以下几个问题：
1.昨天晚上退出重新登陆以后，不自动阅读了，加载网络出错，或者加载不出来书籍，一直转圈圈，同时白天黑夜模式无法开启，不知道是什么BUG，重装不能解决问题。
2.还有一个就是，自动阅读模式下，最小化，屏幕锁定以后，有一定概率，没有时长计算，或者自动停止阅读。以上问题希望能在新版本修复。
3.脚本问题，跟桌面端一样，屏幕锁定以后，无时长计算。

不知道是微信读书官网升级了还是什么原因。电脑：华为matebook  pro 2022. Win版本：win11

**Comment by DoooReyn** [comment]
> 主要有以下几个问题： 1.昨天晚上退出重新登陆以后，不自动阅读了，加载网络出错，或者加载不出来书籍，一直转圈圈，同时白天黑夜模式无法开启，不知道是什么BUG，重装不能解决问题。 2.还有一个就是，自动阅读模式下，最小化，屏幕锁定以后，有一定概率，没有时长计算，或者自动停止阅读。以上问题希望能在新版本修复。 3.脚本问题，跟桌面端一样，屏幕锁定以后，无时长计算。
> 
> 不知道是微信读书官网升级了还是什么原因。电脑：华为matebook pro 2022. Win版本：win11

主要问题是屏幕锁定吧。

这里得看看屏幕锁定指的是关闭显示器还是电脑睡眠/休眠。如果是后者，任何程序都会暂停工作，这是没办法的。

**Comment by DoooReyn** [comment]
> 主要有以下几个问题： 1.昨天晚上退出重新登陆以后，不自动阅读了，加载网络出错，或者加载不出来书籍，一直转圈圈，同时白天黑夜模式无法开启，不知道是什么BUG，重装不能解决问题。 2.还有一个就是，自动阅读模式下，最小化，屏幕锁定以后，有一定概率，没有时长计算，或者自动停止阅读。以上问题希望能在新版本修复。 3.脚本问题，跟桌面端一样，屏幕锁定以后，无时长计算。
> 
> 不知道是微信读书官网升级了还是什么原因。电脑：华为matebook pro 2022. Win版本：win11

测试中

**Comment by DoooReyn** [comment]
![qrcode_1679026686219](https://user-images.githubusercontent.com/9557233/225812366-b76e4a2a-8b22-4641-a565-c2304044fddf.jpg)

QQ交流群: 167970250，欢迎大家😁
