### ISSUE TITLE
【问题】如图，打开报错，重装无用

### ISSUE THREAD

**Issue by just2022try** [DoooReyn/WxReader#12]
![1670835164828](https://user-images.githubusercontent.com/100025239/207002276-f29c40ed-1fbc-488d-87ae-6d3ab77a8f37.png)

**Comment by lin799891** [comment]
同样问题，第一次打开时候还是正常的

**Comment by DoooReyn** [comment]
1. 请退回首页试试
2. 看看有没有开全局VPN或其他代理，如果有，切换一下再试试

**Comment by DoooReyn** [comment]
网络问题请参考 [Wiki-网络错误问题](https://github.com/DoooReyn/WxReader/wiki/%E7%BD%91%E7%BB%9C%E9%94%99%E8%AF%AF%E9%97%AE%E9%A2%98)
