### ISSUE TITLE
不自动点击下一章

### ISSUE THREAD

**Issue by jiang-yuan** [DoooReyn/WxReader#14]
![Snipaste_2023-02-03_17-39-56](https://user-images.githubusercontent.com/36291537/216566623-f949fdaa-f255-408f-b4d7-23c7f6db95f8.png)
win10, 2.0.1版本 如图所示
自动阅读器点击自动以后开始自动向下滚动
把别的工作窗口切到最前挡住wxreader,过一段时间回来看,卡在底部没有自动点击下一章

**Comment by DoooReyn** [comment]
OK，值得试试。

**Comment by DoooReyn** [comment]
测试了一下午，都自动读完两本了，还是没有复现这个问题。

**Comment by jiang-yuan** [comment]
> 测试了一下午，都自动读完两本了，还是没有复现这个问题。

我在win11笔记本上测试也没这个问题,但是我win10的实验室电脑就有这个问题,可能和系统里面的配置有些关系
如果有什么想法的话我可以帮助进一步测试排查
