### ISSUE TITLE
关于Q键退出的问题，希望修复下，谢谢

### ISSUE THREAD

**Issue by lgaying** [DoooReyn/WxReader#16]
想搜本书，只要按下Q键，就立马退出了。能不能修复下该快捷键，谢谢

**Comment by DoooReyn** [comment]
哦吼，这是个bug，我找时间看看。

**Comment by DoooReyn** [comment]
该问题已修复，由于目前累积修复的问题比较少，因此下个版本不会立即发布。见谅。

**Comment by lgaying** [comment]
好的，感谢你的回复。
经过一段时间的使用，确实很方便，再次感谢。
提一个小小的建议，看看是否可以实现，能否增加一个全局老板键，最小化到系统右下角托盘。（该快捷键如果可以自定义最好，个人平常使用ESC按键下方的波浪线那个按键，感觉挺方便的）




在 2023-03-17 11:09:10，"Reyn" ***@***.***> 写道：

该问题已修复，由于目前累积修复的问题比较少，因此下个版本不会立即发布。见谅。
