### ISSUE TITLE
自动阅读突然出问题

### ISSUE THREAD

**Issue by lzc3817** [DoooReyn/WxReader#17]
不自动阅读了，加载网络出错，或者加载不出来书籍，同时白天黑夜模式无法开启，不知道是什么BUG，重装不能解决问题。还有一个就是，自动阅读模式下，最小化，屏幕锁定以后，没有时长计算。以上问题希望能在新版本修复

**Comment by DoooReyn** [comment]
遇到网络错误默认会自动刷新几次，如果还不行，就需要用户手操了。你可以尝试：
1. 手动刷新页面
2. 跳回首页，再打开书籍

另，不自动刷新可以在页面加载完成后反复开关“自动”试试；时长计算可能会滞后，只要自动阅读没问题，一般都会有时长的，不要去实时关注时长变化，间隔十几分钟左右看看就差不多了。

如果还有问题，希望你能上传视频或其他资料方便我跟踪情况，目前来说，我个人的本地版稳定得很，通常都是直接挂到全书读完的。

希望这些能给到你帮助，祝好。

**Comment by DoooReyn** [comment]
“主题切换”功能由于官方最近把 API 隐藏了，目前无法使用模拟点击实现，且暂未找到替代的方法，因此 2.0.2 计划将主题切换设置为“暂不可用”，请用户暂时通过官方按钮手动切换。
