### ISSUE TITLE
UI 页面调整

### ISSUE THREAD

**Issue by LuckyDing-wj** [DoooReyn/WxReader#18]
大佬能不能参考一下 https://gitee.com/diduweiwu-itestdev/wechat-reader-ext，能调整页面宽度的

**Comment by DoooReyn** [comment]
> 大佬能不能参考一下 [https://gitee.com/diduweiwu-itestdev/wechat-reader-ext，能调整页面宽度的](https://gitee.com/diduweiwu-itestdev/wechat-reader-ext)

我的理解是，调整页面宽度直接调整窗口就可以了。

不知道你要的是不是这个。

**Comment by DoooReyn** [comment]
由于太久没有收到反馈，关闭之。
