### ISSUE TITLE
【问题】后台静默阅读会导致自动阅读停止

### ISSUE THREAD

**Issue by LonginusL33T** [DoooReyn/WxReader#2]
点选静默后，从任务栏预览画面可以看出自动阅读已经停止了。微信APP查看阅读时长确实没有增加

**Comment by DoooReyn** [comment]
我测试是可以的，如果实在不行，看来要另辟蹊径了。

**Comment by DoooReyn** [comment]
正式版[v2.0.0](https://github.com/DoooReyn/WxReader/releases/tag/v2.0.0)已经推出，删除了静默模式，直接最小化就好了。
