### ISSUE TITLE
页面白屏幕

### ISSUE THREAD

**Issue by ajiangstudy** [DoooReyn/WxReader#20]
![image](https://user-images.githubusercontent.com/32857102/229262430-cda173a7-59c1-4ced-8a2a-8287339b64cd.png)
之前可以正常用，有一天强制关机就没法用，只能显示工具栏，把工具栏隐藏起来就这样了

**Comment by wanng-ide** [comment]
我也是这个问题！

**Comment by ajiangcool** [comment]
> 我也是这个问题！

在C盘的某个文件下有一个配置文件，删除以后就正常了，具体是哪个配置文件我忘了

**Comment by wanng-ide** [comment]
> 

Work! 非常感谢！

**Comment by DoooReyn** [comment]
解决方案：删除配置文件再重新打开软件。
