### ISSUE TITLE
打开软件白屏

### ISSUE THREAD

**Issue by ssr1282185158** [DoooReyn/WxReader#26]
[0908/164554.821:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

**Comment by DoooReyn** [comment]
关于 Lost UI shared context，可以参考这个[回答](https://groups.google.com/g/cefpython/c/YOPWS0731os/m/7kmg-IReDwAJ)，我后续验证下。

**Comment by DoooReyn** [comment]
邮件收到反馈，重开白屏大部分是用户的异常操作造成配置写入异常引起的，后续会在打开软件时加上一层验证。
