### ISSUE TITLE
【问题】登录界面二维码

### ISSUE THREAD

**Issue by warshon** [DoooReyn/WxReader#3]
Win10-64位系统，使用最新版本v2.0.0-beta.2时，登录二维码显示不出来（显示结果类似于条形码）

**Comment by LonginusL33T** [comment]
beta2版本确实有这个问题。网页右上角的登录按钮可以弹出MODAL，但是只会显示黑色的背景，没有二维码。但点进某一本书，加入书架就可以正常弹出二维码并登录

**Comment by DoooReyn** [comment]
> beta2版本确实有这个问题。网页右上角的登录按钮可以弹出MODAL，但是只会显示黑色的背景，没有二维码。但点进某一本书，加入书架就可以正常弹出二维码并登录

got it.

**Comment by DoooReyn** [comment]
正式版[v2.0.0](https://github.com/DoooReyn/WxReader/releases/tag/v2.0.0)已经推出，解决了上述问题！
