### ISSUE TITLE
能否增加定时开始阅读和定时结束的功能

### ISSUE THREAD

**Issue by aolygc** [DoooReyn/WxReader#30]
如题

**Comment by vadonmo** [comment]
+1

**Comment by DoooReyn** [comment]
让我们提前感谢 [zhu867564473](https://github.com/zhu867564473) 带来的定时功能 [PR](https://github.com/DoooReyn/WxReader/pull/37)，目前该 PR 正在合并中，有好消息会继续同步。

**Comment by DoooReyn** [comment]
> 让我们提前感谢 [zhu867564473](https://github.com/zhu867564473) 带来的定时功能 [PR](https://github.com/DoooReyn/WxReader/pull/37)，目前该 PR 正在合并中，有好消息会继续同步。

PR 已合并。
