### ISSUE TITLE
能否增加批量选中，顺序阅读的功能

### ISSUE THREAD

**Issue by LonginusL33T** [DoooReyn/WxReader#34]
可以在自己书架里批量选中一些待读的书。然后按照这个列表一本读完接着下一本继续读。
这个是否可以实现呢

**Comment by DoooReyn** [comment]
不能。

**Comment by DoooReyn** [comment]
> 可以在自己书架里批量选中一些待读的书。然后按照这个列表一本读完接着下一本继续读。 这个是否可以实现呢

不能，也不现实。
