### ISSUE TITLE
网页微信阅读的界面变了，导致自动失效

### ISSUE THREAD

**Issue by LonginusL33T** [DoooReyn/WxReader#35]
网页微信阅读界面大改了，现在点击“自动”会提示“全书完”，不论当前在第几页
![屏幕截图 2024-04-30 105154](https://github.com/DoooReyn/WxReader/assets/23091103/66151dbd-19dc-4e62-a32c-da478028ef39)

**Comment by jqknono** [comment]
不要使用双栏阅读, 单栏阅读才可以滚动

**Comment by DoooReyn** [comment]
双栏怎么滚动？那就是直接下一页了。这不符合我们的初衷。

**Comment by LonginusL33T** [comment]
> 双栏怎么滚动？那就是直接下一页了。这不符合我们的初衷。

不是，只是微信更新后直接给我默认变成双栏了，我还以为它把单栏删掉了

**Comment by LonginusL33T** [comment]
> 不要使用双栏阅读, 单栏阅读才可以滚动

不是，只是微信更新后直接给我默认变成双栏了，我还以为它把单栏删掉了

**Comment by DoooReyn** [comment]
> > 不要使用双栏阅读, 单栏阅读才可以滚动
> 
> 不是，只是微信更新后直接给我默认变成双栏了，我还以为它把单栏删掉了

好的👌🏻
