### ISSUE TITLE
无法在appdata创建WxReader文件夹

### ISSUE THREAD

**Issue by fevorl** [DoooReyn/WxReader#4]
安装完之后运行没有反应，后来在appdata文件夹下面发现一个WxReader文件，打开显示无法创建WxReader文件夹，手动创建之后能正常运行。

**Comment by DoooReyn** [comment]
> 安装完之后运行没有反应，后来在appdata文件夹下面发现一个WxReader文件，打开显示无法创建WxReader文件夹，手动创建之后能正常运行。

安装位置是？

**Comment by fevorl** [comment]
> 

C:\Program Files\WxReader 上面那个文件夹要创建的路径是C:\Users\linya\AppData\Local
是不是反斜杠的问题？

**Comment by DoooReyn** [comment]
可能是cefpython缓存位置的问题，我把缓存删掉试一下就知道了，下午会检查一下哈

**Comment by DoooReyn** [comment]
果然是 cefpython 缓存路径创建失败了，由于之前测试的时候已经创建好了，所以没发现这个问题。

此问题将在 2.0.1 中修复，请关注 [release](https://github.com/DoooReyn/WxReader/releases) 状态。
