### ISSUE TITLE
点自动阅读就显示“全书完”，然后也并没有自动阅读

### ISSUE THREAD

**Issue by R1Tian** [DoooReyn/WxReader#49]
![image](https://github.com/user-attachments/assets/7d1d12d5-7c5a-452a-97b8-3e566e666d67)

**Comment by DoooReyn** [comment]
不要使用分栏模式，切换成滚动模式。
![image](https://github.com/user-attachments/assets/7a38cb1e-945e-424b-99d7-55663091c089)

**Comment by R1Tian** [comment]
Ok解决了感谢
